import duffel from './duffelClient.js';

/**
 * Search flights via Duffel offer_requests.
 * Returns both the offers and the passenger IDs generated by Duffel —
 * those IDs must be used verbatim when creating the order.
 */
export async function searchFlights({ origin, destination, departureDate, adults }) {
  const response = await duffel.offerRequests.create({
    slices: [{ origin, destination, departure_date: departureDate }],
    passengers: Array.from({ length: Number(adults) }, () => ({ type: 'adult' })),
    return_offers: true,
  });

  return {
    passengers: response.data.passengers, // [{ id, type }] — needed for booking
    offers: response.data.offers,
  };
}

/**
 * Create a Duffel order (booking).
 * travelers: [{ id: duffelPassengerId, given_name, family_name, born_on, email, phone_number, title, gender }]
 */
export async function bookFlight({ offerId, offerAmount, offerCurrency, travelers }) {
  const response = await duffel.orders.create({
    type: 'instant',
    selected_offers: [offerId],
    passengers: travelers,
    payments: [
      {
        type: 'balance',
        currency: offerCurrency,
        amount: offerAmount,
      },
    ],
  });

  return response.data;
}
